version: 0.2

phases:
  install:
    commands:
      - rm -rf /root/.dotnet
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 8.0 --install-dir /root/.dotnet
      - export PATH="/root/.dotnet:$PATH"
      - dotnet --version

  build:
    commands:
      - find . -name global.json -type f -delete
      - rm -f /codebuild/global.json
      - cd MeetVerseBackend/MeetVerse.Api
      - dotnet restore
      - dotnet build -c Release
      - dotnet publish -c Release -o site
      - ls -la site

artifacts:
  base-directory: MeetVerseBackend/MeetVerse.Api/site
  files:
    - '**/*'